# Generated by Django 2.0.6 on 2018-06-09 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(editable=False, max_length=20)),
                ('found_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registry', models.CharField(editable=False, max_length=200)),
                ('assignment', models.CharField(editable=False, max_length=20)),
                ('organization', models.CharField(editable=False, max_length=200)),
                ('organization_address', models.CharField(editable=False, max_length=1000)),
            ],
        ),
    ]
